/**
 * Catches Error for the CLI and prints `UserError` in
 * UI-friendly way. Everything else as it is.
 *
 * @param fn which should be 'error-handled'
 */
export declare function handleError(fn: () => void): void;
